language: clang
sudo: true
services:
  - docker

cache:
  directories:
    - $HOME/docker/

jobs:
  include:

    - stage: Build builder container
      script:
        - ls -als $HOME/docker
        - if [ -f $HOME/docker/cache.tar ]; then docker load -i $HOME/docker/cache.tar; fi
        - OLD_IMAGE_ID=$(docker images --format {{.ID}} milagro-crypto/amcl-builder)
        - docker build --cache-from=milagro-crypto/amcl-builder -t milagro-crypto/amcl-builder .
        - NEW_IMAGE_ID=$(docker images --format {{.ID}} milagro-crypto/amcl-builder)
        - if [ "$OLD_IMAGE_ID" != "$NEW_IMAGE_ID" ]; then docker save milagro-crypto/amcl-builder > $HOME/docker/cache.tar.gz; fi
        - ls -als $HOME/docker

    - &main
      stage: ASan
      env:
        BUILD_GROUP=BUILDS_ASAN
      script:
        - ls -als $HOME/docker
        - docker load -i $HOME/docker/cache.tar
        - docker images
        - make -f Makefile.docker build_group BUILD_GROUP=$BUILD_GROUP

    - <<: *main
      stage: Coverage
      env:
        - BUILD_GROUP=BUILDS_COVERAGE
      install:
        - gem install coveralls-lcov
      after_success:
        - coveralls-lcov /home/travis/build/milagro-crypto/milagro-crypto-c/target/LINUX_64BIT_COVERAGE/coverage/amcl.info

    - &test
      <<: *main
      stage: test alternative environments
      env:
        BUILD_GROUP=BUILDS_64
    - <<: *test
      env:
        BUILD_GROUP=BUILDS_32
    - <<: *test
      env:
        BUILD_GROUP=BUILDS_16
